In [46]:
import numpy as np
import matplotlib.pyplot as plt
import sys
#import sys.path.append("/home/eze/Escritorio/Exactas/04_métodosNuméricos/07_TP/del_git")
import moduloALC
import alc
from src.alc import matrizConfusion

In [47]:
Xt, Yt, Xv, Yv = alc.cargarDataset("./cats_and_dogs")

### Descomposiciones aparte (después)

In [48]:
#Cholesky

In [ ]:
# W = alc.algoritmo1(Xt[:,900:1100], Yt[:,900:1100])
W = alc.algoritmo1(Xt, Yt)
# W = alc.algoritmo3(Xt, Yt)


Tamaño A:  (1536, 2000)


In [41]:
M = W@Xv #[:, 400:600]
M

array([[ 1.12968527e+00,  1.83201881e+00,  1.61247405e+00,
         3.79055305e-01,  3.71976742e-01,  1.16797406e-01,
         6.45392604e-02,  1.05862672e-01,  8.33175257e-01,
         1.94573873e-01,  1.28458579e+00,  2.16270425e-01,
         9.27278868e-01,  6.91051393e-01,  7.24874400e-01,
         9.83195345e-01,  1.20143252e+00,  2.90554409e-01,
         1.06430902e+00,  8.53074823e-01,  8.07204001e-01,
         1.01237610e+00,  3.90470917e-01,  7.24851622e-01,
         3.86870127e-01,  7.35138956e-01,  4.13503822e-01,
         4.61277728e-01,  5.89543053e-02,  1.28225619e+00,
         3.34982230e-01,  1.05041656e+00,  1.70098320e-02,
         1.00438762e+00,  8.70571733e-01,  1.19387350e+00,
         8.54784031e-01,  1.05647983e-01,  4.88088329e-01,
         8.41051935e-01,  7.76135991e-01,  1.50951136e-01,
         9.54369896e-02,  6.88226582e-01,  1.22121648e+00,
         1.74309790e+00,  1.47714019e+00,  6.91381220e-01,
         1.54352105e+00,  1.54200175e+00,  7.81773773e-0

In [42]:
Yv_cortado = Yv #[:, 400:600]
Yv_cortado

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.,

In [43]:
confusion = matrizConfusion(M, Yv_cortado)

In [44]:
confusion

array([[66., 34.],
       [38., 62.]])